<?php

use App\Http\Controllers\Api\AccountingController;
use App\Http\Controllers\Api\AppController;
use App\Http\Controllers\Api\AuthController;
use App\Http\Controllers\Api\ExportController;
use App\Http\Controllers\Api\NotificationController;
use App\Http\Controllers\Api\OperationsController;
use App\Http\Controllers\Api\PlatformController;
use App\Http\Controllers\Api\ReportController;
use App\Http\Controllers\Api\VoiceController;
use Illuminate\Support\Facades\Route;

Route::prefix('v1/voice')->middleware(['auth:sanctum', 'tenant', 'voice.ability', 'throttle:120,1'])->group(function () {
    Route::post('customers/register', [VoiceController::class, 'register'])->middleware('idempotent');
    Route::post('orders', [VoiceController::class, 'store'])->middleware(['idempotent', 'plan.capacity:orders_per_month']);
    Route::post('orders/{order}/measurements', [VoiceController::class, 'measurement'])->middleware('idempotent');
    Route::post('orders/{order}/assign', [VoiceController::class, 'assign'])->middleware('idempotent');
    Route::patch('orders/{order}/status', [VoiceController::class, 'status'])->middleware('idempotent');
    Route::get('search', [VoiceController::class, 'search']);
});

Route::post('v1/auth/login', [AuthController::class, 'login'])->middleware('throttle:10,1');
Route::post('v1/auth/forgot-password', [AuthController::class, 'forgotPassword'])->middleware('throttle:5,1');
Route::post('v1/auth/reset-password', [AuthController::class, 'resetPassword'])->middleware('throttle:5,1');
Route::post('v1/onboarding', [PlatformController::class, 'register'])->middleware('throttle:5,1');
Route::get('v1/plans', [PlatformController::class, 'plans']);
Route::middleware(['auth:sanctum', 'tenant'])->prefix('v1')->group(function () {
    Route::post('auth/logout', [AuthController::class, 'logout']);
    Route::get('auth/two-factor', [AuthController::class, 'twoFactorStatus']);
    Route::post('auth/two-factor/setup', [AuthController::class, 'setupTwoFactor']);
    Route::post('auth/two-factor/confirm', [AuthController::class, 'confirmTwoFactor']);
    Route::delete('auth/two-factor', [AuthController::class, 'disableTwoFactor']);
    Route::get('dashboard', [AppController::class, 'dashboard']);
    Route::get('customers', [AppController::class, 'customers']);
    Route::post('customers', [AppController::class, 'saveCustomer']);
    Route::patch('customers/{customer}', [AppController::class, 'updateCustomer']);
    Route::delete('customers/{customer}', [AppController::class, 'archiveCustomer']);
    Route::post('customers/{customer}/restore', [AppController::class, 'restoreCustomer']);
    Route::get('orders', [AppController::class, 'orders']);
    Route::post('orders', [AppController::class, 'saveOrder'])->middleware('plan.capacity:orders_per_month');
    Route::get('orders/{order}', [AppController::class, 'showOrder']);
    Route::post('orders/{order}/measurements', [AppController::class, 'saveOrderMeasurement']);
    Route::post('orders/{order}/assign', [AppController::class, 'assignOrder']);
    Route::patch('orders/{order}/status', [AppController::class, 'updateOrderStatus']);
    Route::post('orders/{order}/payments', [AppController::class, 'payOrder']);
    Route::delete('orders/{order}', [AppController::class, 'archiveOrder']);
    Route::post('orders/{order}/restore', [AppController::class, 'restoreOrder']);
    Route::get('garments', [AppController::class, 'garments']);
    Route::post('garments', [AppController::class, 'saveGarment'])->middleware('tenant.role:admin,manager');
    Route::patch('garments/{garment}', [AppController::class, 'updateGarment'])->middleware('tenant.role:admin,manager');
    Route::post('garments/{garment}/parts', [AppController::class, 'saveGarmentPart'])->middleware('tenant.role:admin,manager');
    Route::delete('garments/{garment}/parts/{part}', [AppController::class, 'deleteGarmentPart'])->middleware('tenant.role:admin,manager');
    Route::get('employees', [AppController::class, 'employees']);
    Route::post('employees', [AppController::class, 'saveEmployee'])->middleware('tenant.role:admin,manager');
    Route::patch('employees/{employee}', [AppController::class, 'updateEmployee'])->middleware('tenant.role:admin,manager');
    Route::get('inventory', [OperationsController::class, 'inventory'])->middleware('plan.feature:inventory');
    Route::post('inventory', [OperationsController::class, 'saveInventory'])->middleware('plan.feature:inventory');
    Route::post('inventory/{item}/adjust', [OperationsController::class, 'adjust'])->middleware('plan.feature:inventory');
    Route::post('purchases', [OperationsController::class, 'purchase'])->middleware('plan.feature:inventory');
    Route::get('purchases', [OperationsController::class, 'purchases'])->middleware('plan.feature:inventory');
    Route::get('suppliers', [OperationsController::class, 'suppliers'])->middleware('plan.feature:inventory');
    Route::post('suppliers', [OperationsController::class, 'saveSupplier'])->middleware('plan.feature:inventory');
    Route::post('sales', [OperationsController::class, 'sale'])->middleware('plan.feature:inventory');
    Route::get('sales', [OperationsController::class, 'sales'])->middleware('plan.feature:inventory');
    Route::get('expenses', [OperationsController::class, 'expenses']);
    Route::post('expenses', [OperationsController::class, 'saveExpense']);
    Route::post('expenses/{expense}/attachments', [OperationsController::class, 'uploadExpenseAttachment']);
    Route::get('expense-attachments/{attachment}', [OperationsController::class, 'downloadExpenseAttachment']);
    Route::post('expenses/{expense}/approve', [OperationsController::class, 'approveExpense'])->middleware('tenant.role:admin,manager');
    Route::post('attendance', [OperationsController::class, 'attendance']);
    Route::post('work-entries', [OperationsController::class, 'work']);
    Route::post('rentals', [OperationsController::class, 'rental'])->middleware('plan.feature:rentals');
    Route::get('rentals', [OperationsController::class, 'rentals'])->middleware('plan.feature:rentals');
    Route::post('rentals/{rental}/return', [OperationsController::class, 'returnRental'])->middleware('plan.feature:rentals');
    Route::get('workforce', [OperationsController::class, 'workforce']);
    Route::get('payouts', [OperationsController::class, 'payouts']);
    Route::post('payouts', [OperationsController::class, 'payoutBatch'])->middleware('tenant.role:admin,manager');
    Route::get('billing', [PlatformController::class, 'billing']);
    Route::post('billing/portal', [PlatformController::class, 'portal'])->middleware('tenant.role:admin');
    Route::post('billing/checkout', [PlatformController::class, 'checkout'])->middleware('tenant.role:admin');
    Route::get('members', [PlatformController::class, 'members'])->middleware('tenant.role:admin');
    Route::post('members', [PlatformController::class, 'saveMember'])->middleware(['tenant.role:admin', 'plan.capacity:staff_seats']);
    Route::patch('members/{user}', [PlatformController::class, 'updateMember'])->middleware('tenant.role:admin');
    Route::delete('members/{user}', [PlatformController::class, 'deleteMember'])->middleware('tenant.role:admin');
    Route::get('settings', [PlatformController::class, 'showSettings'])->middleware('tenant.role:admin,manager');
    Route::patch('settings', [PlatformController::class, 'settings'])->middleware('tenant.role:admin,manager');
    Route::get('reports/summary', [ReportController::class, 'summary']);
    Route::get('exports', [ExportController::class, 'index'])->middleware('tenant.role:admin,manager');
    Route::post('exports', [ExportController::class, 'store'])->middleware('tenant.role:admin,manager');
    Route::get('exports/{export}/download', [ExportController::class, 'download'])->middleware('tenant.role:admin,manager');
    Route::get('tenant-deletion', [ExportController::class, 'deletionStatus'])->middleware('tenant.role:admin');
    Route::post('tenant-deletion', [ExportController::class, 'scheduleDeletion'])->middleware('tenant.role:admin');
    Route::delete('tenant-deletion/{deletion}', [ExportController::class, 'cancelDeletion'])->middleware('tenant.role:admin');
    Route::get('accounting/trial-balance', [AccountingController::class, 'trialBalance'])->middleware('tenant.role:admin,manager');
    Route::get('customers/{customer}/statement', [AccountingController::class, 'statement'])->middleware('tenant.role:admin,manager');
    Route::post('customers/{customer}/adjustments', [AccountingController::class, 'adjustment'])->middleware('tenant.role:admin,manager');
    Route::get('notifications', [NotificationController::class, 'index']);
    Route::post('notification-templates', [NotificationController::class, 'saveTemplate'])->middleware('tenant.role:admin,manager');
    Route::post('notification-campaigns', [NotificationController::class, 'campaign'])->middleware(['plan.feature:bulk_notifications', 'tenant.role:admin,manager']);
    Route::post('notification-campaigns/occasion', [NotificationController::class, 'occasionCampaign'])->middleware(['plan.feature:bulk_notifications', 'tenant.role:admin,manager']);
    Route::post('orders/{order}/reminder', [NotificationController::class, 'scheduleDeliveryReminder']);
});
Route::middleware(['auth:sanctum', 'super.admin'])->prefix('v1/super-admin')->group(function () {
    Route::get('tenants', [PlatformController::class, 'tenants']);
    Route::get('audits', [PlatformController::class, 'audits']);
    Route::patch('tenants/{tenant}/status', [PlatformController::class, 'suspend']);
    Route::post('tenants/{tenant}/impersonate', [PlatformController::class, 'impersonate']);
});
